[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "STRIPE_PUBLISHABLE_KEY,EMAILJS_PUBLIC_KEY,EMAILJS_SERVICE_ID,EMAILJS_CLIENT_TEMPLATE,EMAILJS_OWNER_TEMPLATE"
